version: '3.7'

services:

  php-fpm:
    build: docker
    container_name: 'php'
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    ports:
      - '7777:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:11
    ports:
      - 15437:5432
    container_name: 'postgresql1'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'progress'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - dump:/app/dump
      - postgresql1:/var/lib/postgresql1/data

volumes:
  dump:
  postgresql1:
  db-data:
###< doctrine/doctrine-bundle ###
